module.exports = {
  SAIL_ROUNDS: 10,
  PAGE_NUMBER: 1,
  PAGE_SIZE: 10,
  DATE_FORMAT: 'YYYY-MM-DD',
  DATE_TIME_FORMAT: 'YYYY-MM-DD, h:mm a',
  ANDROID_APP_VERSION: '2.0',
  IOS_APP_VERSION: '2.0',
  ANDROID_REQUIRED_APP_VERSION: '2.0',
  IOS_REQUIRED_APP_VERSION: '2.0',
  APP_SYSTEMS: ['ios', 'android'],
  DEFAULT_PASS_BCRIPT: "$2a$12$abALp0BzcWCWOxiA27XQ8e8anTNrhXPJm90g.oRnf5x1wGDVdUWSi", // admin#1234
  DEFAULT_PASS: 'admin#1234',
  ORDER_PAYMENT_METHOD: ['PAID', 'INTERNAL', 'CANCELLED', 'COD', 'DECLINED', 'DISPUTED', 'PARTIAL_REFUND', 'PENDING',
    'REFUND_INIT', 'REFUNDED', 'SUBSCRIPTION','PAD','PAYTM','ADVANCE'],
  PRODUCT_QUANTITY_ADD: 1,
  PRODUCT_QUANTITY_REMOVE: 0,
  CART_STATUS: ['ACTIVE', 'INACTIVE', 'DELETED', 'ABANDONED', 'CONSUMED_IN_ORDER'],
  CART_PRODUCT_STATUS: ['ACTIVE', 'INACTIVE'],
  CART_TYPE: ['ONE_TIME_ORDERS', 'SUBSCRIPTION'],
  PRODUCT_TYPE: [
    {
      "id": 1,
      "name": "Variable",
      "slug": "variable"
    },
    {
      "id": 2,
      "name": "Fixed",
      "slug": "fixed"
    }
  ],
  ORDER_FETCH_TYPE: ['BILL_PAYMENTS', 'SUBSCRIPTION', 'ALL'],
  ORDER_FETCH_SUBTYPE: ['ONGOING', 'HISTORY'],
  STOCK_STATUS: ['OUT_OF_STOCK', 'STOCK_AVAILABLE'],
  ORDER_BEFORE_HOURS: 10,
  MONTH_LIST: { JAN: 01, FEB: 02, MAR: 03, APR: 04, MAY: 05, JUN: 06, JUL: 07, AUG: 08, SEP: 09, OCT: 10, NOV: 11, DEC: 12 },
  AMOUNT_TYPE:['CR','DR'],
  PAYMENT_NOTE:['ADVANCE','DUE','ADJUSTMENT'],
};
